
package Frames;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import models.DbConn;
import models.FullPlace;
import models.ReservedPlace;


public class Places extends javax.swing.JFrame {

    
    public Places() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btA1 = new javax.swing.JButton();
        btA2 = new javax.swing.JButton();
        btA3 = new javax.swing.JButton();
        btA4 = new javax.swing.JButton();
        btA5 = new javax.swing.JButton();
        btB1 = new javax.swing.JButton();
        btB2 = new javax.swing.JButton();
        btB3 = new javax.swing.JButton();
        btB4 = new javax.swing.JButton();
        btB5 = new javax.swing.JButton();
        btC1 = new javax.swing.JButton();
        btC2 = new javax.swing.JButton();
        btC3 = new javax.swing.JButton();
        btC4 = new javax.swing.JButton();
        btC5 = new javax.swing.JButton();
        btD1 = new javax.swing.JButton();
        btD2 = new javax.swing.JButton();
        btD3 = new javax.swing.JButton();
        btD4 = new javax.swing.JButton();
        btD5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btA1.setBackground(new java.awt.Color(0, 255, 0));
        btA1.setText("A1");
        btA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btA1ActionPerformed(evt);
            }
        });

        btA2.setBackground(new java.awt.Color(0, 255, 0));
        btA2.setText("A2");

        btA3.setBackground(new java.awt.Color(0, 255, 0));
        btA3.setText("A3");

        btA4.setBackground(new java.awt.Color(0, 255, 0));
        btA4.setText("A4");

        btA5.setBackground(new java.awt.Color(0, 255, 0));
        btA5.setText("A5");

        btB1.setBackground(new java.awt.Color(0, 255, 0));
        btB1.setText("B1");

        btB2.setBackground(new java.awt.Color(0, 255, 0));
        btB2.setText("B2");

        btB3.setBackground(new java.awt.Color(0, 255, 0));
        btB3.setText("B3");

        btB4.setBackground(new java.awt.Color(0, 255, 0));
        btB4.setText("B4");

        btB5.setBackground(new java.awt.Color(0, 255, 0));
        btB5.setText("B5");

        btC1.setBackground(new java.awt.Color(0, 255, 0));
        btC1.setText("C1");

        btC2.setBackground(new java.awt.Color(0, 255, 0));
        btC2.setText("C2");
        btC2.setActionCommand("btC2");

        btC3.setBackground(new java.awt.Color(0, 255, 0));
        btC3.setText("C3");

        btC4.setBackground(new java.awt.Color(0, 255, 0));
        btC4.setText("C4");

        btC5.setBackground(new java.awt.Color(0, 255, 0));
        btC5.setText("C5");

        btD1.setBackground(new java.awt.Color(0, 255, 0));
        btD1.setText("D1");

        btD2.setBackground(new java.awt.Color(0, 255, 0));
        btD2.setText("D2");

        btD3.setBackground(new java.awt.Color(0, 255, 0));
        btD3.setText("D3");

        btD4.setBackground(new java.awt.Color(0, 255, 0));
        btD4.setText("D4");

        btD5.setBackground(new java.awt.Color(0, 255, 0));
        btD5.setText("D5");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        jButton2.setText("Exit Program");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(btA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btD1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(btA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btC3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(btB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btD3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btB4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(btA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btA5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(btB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btC4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(btD4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btC5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(btD5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btA1)
                    .addComponent(btA2)
                    .addComponent(btA3)
                    .addComponent(btA4)
                    .addComponent(btA5))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btB1)
                    .addComponent(btB2)
                    .addComponent(btB3)
                    .addComponent(btB4)
                    .addComponent(btB5))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btC1)
                    .addComponent(btC2)
                    .addComponent(btC3)
                    .addComponent(btC4)
                    .addComponent(btC5))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btD1)
                    .addComponent(btD2)
                    .addComponent(btD3)
                    .addComponent(btD4)
                    .addComponent(btD5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btA1ActionPerformed

    }//GEN-LAST:event_btA1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DbConn db = new DbConn();
        List<FullPlace> list = db.listFullPlace();
        for (FullPlace fullPlace : list) {
            if (fullPlace.getReservedPlace().equals("A1")) {
                btA1.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("A2")) {
                btA2.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("A3")) {
                btA3.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("A4")) {
                btA4.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("A5")) {
                btA5.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("B1")) {
                btB1.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("B2")) {
                btB2.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("B3")) {
                btB3.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("B4")) {
                btB4.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("B5")) {
                btB5.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("C1")) {
                btC1.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("C2")) {
                btC1.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("C3")) {
                btC3.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("C4")) {
                btC4.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("C5")) {
                btC5.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("D1")) {
                btD1.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("D2")) {
                btD2.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("D3")) {
                btD3.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("D4")) {
                btD4.setBackground(Color.red);
            }
            if (fullPlace.getReservedPlace().equals("D5")) {
                btD5.setBackground(Color.red);
            }

        }

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Registration().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Places().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA1;
    private javax.swing.JButton btA2;
    private javax.swing.JButton btA3;
    private javax.swing.JButton btA4;
    private javax.swing.JButton btA5;
    private javax.swing.JButton btB1;
    private javax.swing.JButton btB2;
    private javax.swing.JButton btB3;
    private javax.swing.JButton btB4;
    private javax.swing.JButton btB5;
    private javax.swing.JButton btC1;
    private javax.swing.JButton btC2;
    private javax.swing.JButton btC3;
    private javax.swing.JButton btC4;
    private javax.swing.JButton btC5;
    private javax.swing.JButton btD1;
    private javax.swing.JButton btD2;
    private javax.swing.JButton btD3;
    private javax.swing.JButton btD4;
    private javax.swing.JButton btD5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
